import Head from "next/head";
import { EmblaCarousel } from "@/components/EmblaCarousel/EmblaCarousel";
import Swiper from "@/components/Swiper/Swiper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EmblaCarousel />
      <div style={{ margin: '100px 0' }} />
      <Swiper />
    </>
  );
}
